### ISSUE TITLE
[RFC] Manual CIDR specification and Centralized Viewers

### ISSUE THREAD

**Issue by chelma** [arkime/aws-aio#116]
## User Need
* Users need the ability to specify the CIDR of the Capture VPC (enterprise customer feedback)
* Users need the ability to have the Viewer's IP pull from a different CIDR than the rest of the resources in the Capture VPC (enterprise customer feedback)
* Users want the ability to have centralized Viewers that surface details from multiple Arkime Clusters spread across different accounts and regions

## Assumptions
* The Capture Nodes, OS Domain, etc and other capture-related resources do not need to initiate connections to the Viewer Nodes
* Viewer Nodes need to initiate connections to the OS Domain
* In the centralized-Viewer scenario, the central Viewer just needs access to the individual Clusters' OS Domains and PCAP Buckets, not the other Viewers
* If users are manually specifying CIDRs for their VPCs, they fall in the power-user category and can be expected to find non-conflicting IP spaces

## Proposal

* Move the Viewer Nodes to a separate VPC connected to the Capture VPC via a TGW
* Update the `create-cluster` command to optionally accept CIDRs for the Capture and Viewer VPCs.  If not supplied, the CLI will pick reasonable defaults.
* If the user does not specify the optional CIDR for the Viewer Nodes, the we use the original approach of sticking the nodes in the Capture VPC and selecting their IPs from that.
* Re-use the new Viewer VPC concept to handle the centralized-Viewer scenario in the future

### Why move the Viewer Nodes into a separate VPC?
Moving the Viewer Nodes into a separate VPC enables us to better leverage CDK/CloudFormation for infrastructure management and enables us to re-use the new Viewer VPC for both the single-Viewer (the Viewer attached to an Arkime Cluster by default) and centralized-Viewer (a new Viewer in perhaps a different account/region that connects to many Arkime Clusters) scenarios.

In the event that a user wants the Capture and Viewer Nodes to use different CIDRs (such as one enterprise customer expressed a desire for), there are a two approaches that can be taken.

The first approach is to create the Capture VPC using the CIDR for the Capture Nodes, then use an API call to the additional Viewer CIDR to the Capture VPC, then provision new subnets in the Capture VPC with the Viewer CIDR, then provision the Viewer Nodes in those new subnets.  This is possible but requires the use of a CloudFormation Custom Resource to accomplish due to it not being possible to add the second CIDR using CloudFormation.  Custom Resources are flaky, complex, and best considered a "design smell" in that there's usually a sign a design is straying from the intent of the API designers.  Importantly, they introduce unusual and unexpected failure modes into deploy-time (i.e. "run a Lambda during Cfn deploy-time" has a lot more ways to fail than *not* doing that).  Additionally, this approach does not help us solve the centralized-viewer problem, meaning we'd need a different solution for that as well (likely approach 2, below).  For these reasons, this approach is not ideal.

The second approach is to turn the Viewer CIDR into a new VPC that connects to the Capture CIDR via TGW.  This better leverages the CloudFormation Spec for VPC, simplifies management by enabling the CDK to do more auto-magic selection of default options, reduces the number of failure modes by avoiding the Custom Resource, and enables us to re-use our solution for the centralized-Viewer.  TGWs allow for cross-account, cross-region access so the only thing distinguishing the single-Viewer and centralized-Viewer scenarios from an infrastructure perspective is the number of TGW VPC Attachments and the Arkime Configuration deployed to the Viewer Nodes (e.g. they need to know about multiple OS Domains instead of just one).  The primary disadvantage of this approach is cost - $0.05/hr for each VPC Attachment and $0.02/GB sent over the attachments (according to the pricing docs).  Of these two, the hourly attachment cost seems more consequential as the amount of data the Viewers will consume seems like it should be quite small given human interaction is required.

**Comment by chelma** [comment]
Had a thought - one option would be to only do the more sophisticated setup of moving the Viewers to their own VPC if the user specifies a Viewer CIDR.  This means that non-power-users will get a simpler setup.  Will update the proposal above.

**Comment by awick** [comment]
Few questions:
* since we are using VPC OS Domains, and I assume it will live in the Capture VPC, does the Viewer VPC talk to the OS Domain using VPC Attachments or something else?
* since the viewer and capture VPCs don't talk to each other, why is the TGW needed? or is that for the above? 
* is it really the viewer ip that needs to be special or is it the viewer LB ip?

**Comment by awick** [comment]
1-3. yep agree
4. ok, this was my question. So the TGW is required because of how the viewer VPC would need to reach into the capture VPC to talk to the OS Domain. There is no way to "mount" the OS Domain into both VPCs.
5. was just trying to clarify the requirement. `Users need the ability to have the Viewer's IP pull from a different CIDR than the rest of the resources in the Capture VPC (enterprise customer feedback)` -- I don't think they care about the viewer IP, they only care about what IP they will be using for the UI, which is the viewer LB? I agree the reset of what you wrote might follow from that, just want to make sure I'm not missing something

**Comment by chelma** [comment]
4.  I believe so, yes.  There might be other ways to do this (the AWS catalogue is enormous), but this is the best way I'm aware of.
5. Ah, good callout.  I'm not sure with regards to the particular enterprise user we talked to.  It sounded like they may want the ability to assign their own DNS entries to the Viewer Node IPs or just use the DNS name of the LB.  Fortunately, I'm not sure our design changes either way.

**Comment by chelma** [comment]
Discussed the specifics out-of-band.  Overall, it seems like a viable approach but has two notable downsides:
* Users need to plan out IP space allocation for all Capture/Viewer VPCs that want to communicate to eachother
* Use of TGWs may spur additional scrutiny during security review

An alternative approach not yet discussed is to use OpenSearch managed VPC Endpoints [1] [2].  These have neither of the downsides of the TGW approach mentioned just above.  However, they have new downsides of their own:
* They cannot be created by CloudFormation (meaning we'd require a Custom Resource, which we were trying to avoid)
* They cannot be used to create cross-region links, meaning that we can't use them for our centralized viewer solution.

[1] https://docs.aws.amazon.com/opensearch-service/latest/developerguide/vpc-interface-endpoints.html
[2] https://aws.amazon.com/blogs/big-data/simplify-private-network-access-for-solutions-using-amazon-opensearch-service-managed-vpc-endpoints/

**Comment by chelma** [comment]
Got some additional data points from other domain experts; the TGW approach does appear to be the correct approach.  Moving forward with that.
