### ISSUE TITLE
[TRACKING] Phase 1 - Basic Create/Delete

### ISSUE THREAD

**Issue by chelma** [arkime/aws-aio#3]
## Description
For phase 1, we will focus on creating a CLI with basic creation/deletion for adding an Arkime installation into an existing AWS Account with existing VPCs/traffic sources.  Issue will be used to outline the overall progress of phase 1.

Still need to add the code/command to tear the demo traffic stacks down.

## Tasks
* DONE: Create CDK stacks for demo traffic generation (https://github.com/arkime/cloud-demo/pull/1)
* https://github.com/arkime/cloud-demo/issues/4
* https://github.com/arkime/cloud-demo/issues/5
* https://github.com/arkime/cloud-demo/issues/6
* https://github.com/arkime/cloud-demo/issues/7

## Follow-up Items
* https://github.com/arkime/cloud-demo/issues/12
* https://github.com/arkime/cloud-demo/issues/18

**Comment by chelma** [comment]
Follow-up Work (CLI):
* add-vpc: Add unit tests
* create-cluster: Update to provide uses with viewer URL/username/password when finished
* destroy-cluster: Update to check if the cluster is monitoring VPCs, abort if it is
* remove-vpc: Add unit tests

Follow-up Work (CDK):
* Capture Nodes Stack: Configure Auto-Scaling; currently wonky/broken
* Mirror Stack: Get the user's VPC cidr and use for filter rules instead of hardcoding
* Single Quotes: Action this open issue to change to a consistent quote style (https://github.com/arkime/cloud-demo/issues/18)

Follow-up Work (Workstreams):
* Mirroring Resilience: Create mechanisms to make traffic mirroring more resilient to changes in user traffic load, network configuration (changes in subnets), and traffic soruces (changes in ENIs, short-lived ENIs)
* Configurable Capture: Create mechanisms to surface capture process configuration to the user and enable updates of that configuration
* Centralized Viewer: Create mechanisms to enable a single Viewer to surface details from many Arkime Clusters
* Viewer HTTPS: Create mechanisms (either code or a written guide) to enable HTTPS for the Viewer Nodes
* Cross-Account Capture: Create mechanisms to enable users to capture traffic from VPCs they own in other accounts (but the same region)
* Global Viewer: Create mechanisms to enable Viewers to surface details from Arkime Clusters in other regions
* User Management: Create mechanisms to enable better user management/AuthN/AuthZ than just the basic version provided by the Viewer

**Comment by chelma** [comment]
![cloud_arkime_design](https://user-images.githubusercontent.com/25470211/232084792-bb9115fa-4936-4f06-b986-c5e384a4c841.png)

**Comment by awick** [comment]
couple other thoughts
* viewer https support with maybe user provided dns name should probably be higher than centralized
* with capture auto scaling would like to see ability to optionally specify min/max as cli params
* add cli ability to set/update the s3 lifecycle policy for pcap files with a X (90?) day default
* I think it would be nice if there was a cli command to get the viewer password (assuming the user has the perm)

**Comment by awick** [comment]
Would also like to figure out how we should represent capture node names, since using the ip is kind of useless. Maybe something like "<cluster name>-<monitored vpc>-<instanceid>". Although if we share capture nodes across vpcs maybe just "<cluster>-<instanceid"

**Comment by chelma** [comment]
Acceptance criteria met for this phase; follow-up work tracked in a new issue (https://github.com/arkime/cloud-demo/issues/20).  Resolving.
