### ISSUE TITLE
Support cluster settings

### ISSUE THREAD

**Issue by awick** [arkime/aws-aio#34]
An Arkime cluster has several settings that need to be settable at creation time and updatable.

| Name | Argument | Default | What  |
|--------|--------|--------|--------|
| Retention SPI | --spi-days [days] | 30 | Number of days to keep session data. Implemented when calling the db.pl ism option |
| Retention PCAP | --pcap-days [days] | 30 | Number of days to keep PCAP data. Implemented with the S3 Lifecycle policy |
| Retention History | --history-days [days] | 90 | Number of days to keep the History data. Implemented with t he db.pl --history option |
| Session Replication | --replicas [num] | 0 | The OpenSearch replicas for the sessions3 indices. Implemented with the db.pl --replicas option |
| Expected Gbps | --expected-gbps | 1 | The expected Gbps this cluster should handle. For now the max should be 10, since that is the default max for a GWLB. This will be used to calculated the initial OpenSearch and capture sizing, see below |

### OpenSearch Scaling Calculations, assuming 3% PCAP to SPI ratio
Updating the opensearch scaling can be dangerous, so we will have to be smart about it. Once an instance type is picked we should stick with that, unless that instance type can no longer support what we need.

I suggest we pick 3 instance types and run the calculations across them all and use AI (lol) to pick.
We should NOT try and support every instance type available.
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/limits.html
At least one instance type should support the larger EBS volumes (7TB+).

SessionsGB = ($replicas + 1) * ($spiDays * 24 * 60 * 60) * $ExpectedGbps/8 * 0.03
NodesByGB = $SessionsGB/$GBPerOSNode
Nodes = MAX($NodesByGB, $replicas + 1)

So for example if you wanted 30 days of 10Gbps that would be 97TB of required storage.

### Capture sizing - Lets start with 4Gbps per node for now.
CEIL($ExpectedGbps/4)

**Comment by chelma** [comment]
Spun off a sub-task to do the capture cluster sizing first - https://github.com/arkime/cloud-demo/issues/52

**Comment by chelma** [comment]
I think we've implemented all parts of this tracking ticket.  Resolving.
