### ISSUE TITLE
Make S3 Policies user-configurable

### ISSUE THREAD

**Issue by chelma** [arkime/aws-aio#61]
## Description
As part of making our Arkime Cluster more configurable, add a way for the user to specify an expiration policy for the PCAP files in S3 (`--retention-pcap`), with a default retention period of 30 days.  Also, use the task as an opportunity to apply any lightweight S3 best practices that you identify in the process.

Note: This is a sub-task of https://github.com/arkime/aws-aio/issues/34

## Acceptance Criteria
* S3 retention policy configurable via the CLI, and behaves like the other CLI capacity options

**Comment by chelma** [comment]
A couple quick standouts for additional tweaks:
* Enforcing SSL when accessing bucket objects (one-line change)
* Changing storage tiers from `S3 Standard` to `S3 Standard - Infrequent Access`.

Regarding the `Infrequent Access` tier, when compared to the default `S3 Standard`:
* It has the same latency/throughput/durability
* It costs ~40% less for storage and ~250% more for retrieval in us-east-2
* It has a minimum storage duration of 30 days.  Objects stored for less than 30 days are billed as if they were stored for 30 days.

Overall, given the usage pattern for Arkime, it seems like a good fit despite the quirk around the minimum storage duration.

**Comment by chelma** [comment]
Hmm, I misread the pricing docs.  More specifically, for `S3 Standard - Infrequent Access`, you pay:
* 100% more for PUT, COPY, POST, LIST requests
* 250% more for GET, SELECT, and all other requests
* A data retrieval fee ($0.01/GB in us-east-2) that the `S3 Standard` tier does NOT charge at all

Elyse will take a look at some metrics for average PCAP file size so we can be a bit more informed on the tradeoffs.

**Comment by awick** [comment]
Need to add s3StorageClass= to docker-capture-node/arkime_config.ini and pass variable into it.

**Comment by chelma** [comment]
AC met; resolving
